Sylius/Sylius-Docs

book/architecture.rst, book/installation.rst, book/payments.rst, bundles/SyliusResourceBundle/index_resources.rst
=> Minor fixes

bundles/SyliusPromotionBundle/action_applicator.rst, bundles/SyliusPromotionBundle/applying_promotions.rst, bundles/SyliusPromotionBundle/coupon_based.rst, bundles/SyliusPromotionBundle/index.rst, bundles/SyliusPromotionBundle/installation.rst, bundles/SyliusPromotionBundle/models.rst, bundles/SyliusPromotionBundle/rule_checker.rst, bundles/SyliusPromotionBundle/summary.rst
@aRn0D https://github.com/Sylius/Sylius-Docs/pull/245
=> PromotionBundle name changed in doc (removed the "s")

bundles/SyliusSettingsBundle/installation.rst, bundles/general/mapping_relations.rst
=> Improved bundle registration order note

api/authorization.rst, api/index.rst, api/map.rst.inc
| Doc fix?      | no
| New docs?     | yes
| Fixed tickets |
=> API authorization

bundles/SyliusResourceBundle/configuration.rst
Q  | A
----|----
Doc fix? | yes
New docs? | no
Fixed tickets |  -
=> [ResourceBundle] Configuration chapter

book/environments.rst
=> Fixed copy & paste typo in 'test' environment paragraph

bundles/SyliusResourceBundle/form_type.rst, bundles/SyliusResourceBundle/index.rst
Q  | A
----|----
Doc fix? | no
New docs? | yes
Fixed tickets |  -
=> [ResourceBundle] Extra form types chapter

bundles/SyliusResourceBundle/doctrine.rst
Q  | A
----|----
Doc fix? | no
New docs? | yes
Fixed tickets |  -
=> [ResourceBundle] mapping driver fixes

bundles/SyliusFlowBundle/installation.rst
I think that this is easier to understand
=> improve naming for configurable things

bundles/SyliusResourceBundle/configuration.rst
- Fix mistype entity/document
- Fix inconsistency in example naming (name/key)
=> Update SyliusResourceBundle configuration

components/Order/order_and_items.rst
=> [Order] Remove unused fields from Order

book/payments.rst, components/Payment/model.rst
Improved docs to correspond with new fee calculators funcionality in SyliusPaymentBundle.
=> Changes in Payment component

bundles/SyliusAddressingBundle/installation.rst
=> Added required SyliusTranslationBundle configuration

book/payments.rst
Various info gathered during a debugging session that could prove very useful for future reference.
=> Add troubleshooting info to payments.rst

cookbook/extending-menu.rst
Re: commit  https://github.com/Sylius/Sylius/commit/543a77709ce5414d73b7f62fb999c56d7d74f875
=> Update extending-menu.rst for new frontend events

components/Payment/model.rst
Change in Payment model to make Payments softdeleteable.
=> [Payments] Added deletedAt field on Payment model

bundles/SyliusResourceBundle/installation.rst
Needed for paginator when using fos rest
=> Added HateoasBundle to installation docs

bundles/SyliusGridBundle/custom_filter.rst
=> [Grid] Fixed wrong tags in custom filter configuration

bundles/SyliusOrderBundle/summary.rst
| Fixed tickets | Sylius/Sylius#2878
=> [OrderBundle] Fixed configuration reference

components/Resource/repository.rst
=> [Resource] RepositoryInterface ref link label

components/Resource/model.rst
=> [Resource] Add missing ref label before timestable interface

api/checkouts.rst, api/orders.rst, components/Order/basic_usage.rst, components/Order/models.rst
PR changes: https://github.com/Sylius/Sylius/pull/3536
=> Adding docs about renaming label to type on adjustment

components/Order/basic_usage.rst, components/Order/interfaces.rst, components/Order/models.rst
[Order] Documentation of Order component
=> [Order] Fix documentation 

components/Originator/basic_usage.rst, components/Originator/index.rst, components/Originator/installation.rst, components/Originator/interfaces.rst, components/index.rst, components/map.rst.inc
=> [Originator] Documentation of Originator component

components/Translation/basic_usage.rst, components/Translation/index.rst, components/Translation/installation.rst, components/Translation/interfaces.rst, components/Translation/models.rst, components/index.rst, components/map.rst.inc
=> [Translation] Documentation of Translation component

components/Channel/basic_usage.rst, components/Channel/index.rst, components/Channel/installation.rst, components/Channel/interfaces.rst, components/Channel/models.rst, components/index.rst, components/map.rst.inc
=> [Channel] Documentation of Channel component

components/Mailer/basic_usage.rst
| Q                    | A
| -------------------| ---
| Doc fix?          | [yes]
| New docs?     | [no] 
| Fixed tickets   | [no]
=> [Mailer] Fix code-blocks

components/Storage/basic_usage.rst, components/Storage/index.rst, components/Storage/installation.rst, components/Storage/interfaces.rst, components/index.rst, components/map.rst.inc
=> [Storage] Documentation of Storage component

components/Locale/interfaces.rst
Q 	|A
------|------
Doc fix?| 	yes
New docs?| 	no
=> [Locale] Documentation update

components/Promotion/interfaces.rst, components/Promotion/models.rst
Q 	|A
------|-----
Doc fix?| 	yes
New docs?| no
Fixed tickets? |	-
=> [Promotion] Documentation update

components/Currency/interfaces.rst
Q 	|A
-----|-----
Doc fix?| 	yes
New docs?| 	no
=> [Currency] Update documentation

components/Payment/interfaces.rst, components/Payment/models.rst
=> [Payment] Update docs

components/Report/interfaces.rst
Q 	|A
------|-----
Doc fix?| 	yes
New docs?| 	no
=> [Report] Documentation update

components/Mailer/interfaces.rst
Q 	|A
------|--------
Doc fix? 	|yes
New docs?| 	no
=> [Mailer] Update documentation

components/Archetype/interfaces.rst
| New Docs?  | no
| Fixed tickets ?    | -
=> [Archetype] Update documentation

components/Shipping/basic_usage.rst, components/Shipping/interfaces.rst, components/Shipping/models.rst
=> [Shipping] Documentation update

components/Taxation/basic_usage.rst, components/Taxation/interfaces.rst, components/Taxation/models.rst
|Q 	|A|
-------|-----
Doc fix?| 	yes
New docs?| 	no
=> [Taxation] Update docs

bundles/SyliusAddressingBundle/summary.rst, bundles/SyliusArchetypeBundle/configuration.rst, bundles/SyliusAttributeBundle/configuration.rst, bundles/SyliusCartBundle/summary.rst, bundles/SyliusContactBundle/configuration.rst, bundles/SyliusContactBundle/index.rst, bundles/SyliusInventoryBundle/summary.rst, bundles/SyliusMailerBundle/configuration.rst, bundles/SyliusOrderBundle/summary.rst, bundles/SyliusProductBundle/summary.rst, bundles/SyliusPromotionBundle/summary.rst, bundles/SyliusRbacBundle/configuration.rst, bundles/SyliusReportBundle/summary.rst, bundles/SyliusResourceBundle/configuration.rst, bundles/SyliusSettingsBundle/summary.rst, bundles/SyliusShippingBundle/summary.rst, bundles/SyliusTaxationBundle/summary.rst, bundles/SyliusTaxonomyBundle/summary.rst, bundles/SyliusVariationBundle/configuration.rst
| New docs?     | yes
| Fixed tickets |  no
=> Configuration trees docs update in Bundles

bundles/SyliusResourceBundle/configuration.rst
fix error introduced by https://github.com/Sylius/Sylius-Docs/pull/383
=> fix Resource Bundle configuration tree

components/Variation/interfaces.rst, components/Variation/models.rst
Q 	|A
-------|------
Doc fix?| 	yes
New Docs?| 	no
Fixed tickets ?| 	-
=> [VariationBundle] Update documents

components/Channel/interfaces.rst
Q 	|A
------|-------
Doc fix?| 	yes
New Docs?| 	no
Fixed tickets ?| 	-
=> [Channel] Update documentation

components/Rbac/interfaces.rst
Q 	|A
--------|--------
Doc fix?| 	yes
New Docs?| 	no
Fixed tickets ?| 	-
=> [Rbac] Update documentation 

components/Order/interfaces.rst, components/Order/models.rst
=> [Order] OrderItemUnits docs

components/Addressing/basic_usage.rst, components/Addressing/models.rst
=> [Addressing] Updated documentation of Addressing component

components/Pricing/interfaces.rst
=> [Pricing] Fix link in Pricing component

bundles/SyliusOrderBundle/models.rst, bundles/SyliusOrderBundle/services.rst, bundles/SyliusOrderBundle/summary.rst
=> [Order] OrderItemUnits docs improvements

bundles/SyliusReportBundle/installation.rst
Q 	|A
------|------
Doc fix?| 	yes
New docs?| 	no
Fixed tickets| 	-
=> [ReportBundle] Documentation update

components/Attribute/basic_usage.rst
To be implemented hasAttributeByCode/getAttributeByCode
=> Add Collection type hint + add hasAttributeByCode/getAttributeByCode

components/Attribute/basic_usage.rst
Not sure if these are the right values.
=> Remove DefaultAttributeTypes

components/Attribute/basic_usage.rst
Otherwise there will be an Exception here:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Attribute/Model/AttributeValue.php#L129
=> Move setAttribute

bundles/SyliusResourceBundle/create_resource.rst, bundles/SyliusResourceBundle/update_resource.rst
Update documentation to reflect changes introduced in [Sylius PR #4101](https://github.com/Sylius/Sylius/pull/4101)
=> [ResourceBundle] Update route configuration for use custom options in form

PULL_REQUEST_TEMPLATE.md
Added pull request template similar to [this from Sylius](https://github.com/Sylius/Sylius/blob/master/PULL_REQUEST_TEMPLATE.md).
=> Implement PR template

api/promotions.rst, bundles/SyliusPromotionBundle/models.rst, bundles/SyliusPromotionBundle/rule_checker.rst
Changes in promotion docs, according to https://github.com/Sylius/Sylius/pull/4249 and https://github.com/Sylius/Sylius/pull/4266
=> [Promotion] Changes in promotion docs

behat/how-to-use-transformers.rst, behat/index.rst, behat/map.rst.inc
| Doc fix?      | no
| New docs?     | yes
| Fixed tickets |
=> [Behat] Explain transformers usage

index.rst, migration/index.rst, migration/introduction.rst, migration/map.rst.inc
=> Removed empty "Migration Guide" section

guide/installation.rst
| Doc fix?        | yes
| New docs?   | no
=> The User Guide - minor fixes
